// Hand-written tickets in Spanish, German, French, and Portuguese, one or
// more per team, for the routing level in other languages. Slots as in
// generate.ts.

import type { TicketTemplate } from "./generate.ts";

const T = (
  team: TicketTemplate["team"],
  urgency: TicketTemplate["urgency"],
  refund: boolean,
  subject: string,
  message: string,
  why: string,
): TicketTemplate => ({ team, urgency, refund, subject, message, why });

export const TICKETS_TRANSLATED: Record<string, TicketTemplate[]> = {
  es: [
    T(
      "billing",
      2,
      true,
      "Cobro duplicado en septiembre",
      "Hola:\n\nNos han cobrado {amount} dos veces por la misma factura ({invoice}). Necesitamos que nos devuelvan el segundo cargo antes del cierre del viernes.\n\nGracias,\n{first}",
      "un cobro duplicado que hay que reembolsar",
    ),
    T(
      "technical",
      3,
      false,
      "No se imprimen etiquetas en ningún almacén",
      'La generación de etiquetas falla en todos nuestros almacenes {since}. Cada intento devuelve "{error}" y tenemos {loads} cargas esperando en los muelles.\n\n{first}',
      "una caída total de las etiquetas",
    ),
    T(
      "account_access",
      2,
      false,
      "No puedo entrar tras cambiar de móvil",
      "Cambié de teléfono y los códigos de verificación ya no funcionan. Soy la única persona de despacho hoy y no puedo reservar nada.\n\n{first}",
      "un usuario bloqueado por la verificación en dos pasos",
    ),
    T(
      "sales",
      1,
      false,
      "Presupuesto para el módulo de patio",
      "Queremos precios del módulo de gestión de patio para tres centros antes de la reunión de presupuesto de la semana que viene.\n\n{first}",
      "una petición de presupuesto",
    ),
    T(
      "privacy_security",
      2,
      false,
      "Solicitud de supresión de datos (RGPD)",
      "Un antiguo empleado nos ha pedido que borremos sus datos personales. Eliminen, por favor, la cuenta de j.moreau@{domain} y todos sus datos, y confírmenlo por escrito.\n\n{first}",
      "una solicitud de supresión de datos personales",
    ),
  ],
  de: [
    T(
      "billing",
      1,
      false,
      "Falsche Bestellnummer auf der Rechnung",
      "Hallo, auf Rechnung {invoice} steht PO-11842, unsere Bestellung lautet aber PO-11924. Wir brauchen keine Erstattung, nur ein korrigiertes PDF für die Kreditorenbuchhaltung.\n\n{first}",
      "eine Rechnungskorrektur",
    ),
    T(
      "technical",
      2,
      false,
      "Frachtraten für einen Spediteur schlagen fehl",
      'Seit gestern liefert die Ratenabfrage für {carrier} nur "{error}", alle anderen funktionieren. Wir buchen telefonisch, aber die Disposition wird deutlich langsamer.\n\n{first}',
      "eine defekte Schnittstelle mit Umweg",
    ),
    T(
      "account_access",
      3,
      false,
      "SSO für die ganze Firma ausgefallen",
      'Seit unsere IT heute früh das SAML-Zertifikat erneuert hat, kann sich bei {company} niemand mehr über Okta anmelden. Alle {users} Nutzer sehen "invalid signature".\n\n{first}',
      "alle Nutzer ausgesperrt",
    ),
    T(
      "sales",
      2,
      false,
      "Verlängerungsangebot bis Donnerstag benötigt",
      "Unser Vertrag läuft am 30. aus und der Einkauf braucht das finale Angebot für {users} Lizenzen bis Donnerstag, sonst verschiebt sich die Verlängerung um ein Quartal.\n\n{first}",
      "ein Verlängerungsangebot mit Frist",
    ),
    T(
      "privacy_security",
      3,
      false,
      "Verdacht auf kompromittiertes Konto",
      "Ein Nutzer meldet, dass Sendungen an eine unbekannte Adresse umgeleitet werden, und das Audit-Log zeigt nächtliche Anmeldungen aus dem Ausland. Bitte sperren Sie das Konto und helfen Sie uns bei der Untersuchung.\n\n{first}",
      "eine wahrscheinliche Kontoübernahme",
    ),
  ],
  fr: [
    T(
      "billing",
      1,
      true,
      "Avoir pour l'indisponibilité de la semaine dernière",
      "Bonjour, notre contrat Enterprise prévoit un avoir lorsque la disponibilité passe sous 99,9 %. La panne des étiquettes de mardi a duré environ quatre heures. Pouvez-vous l'appliquer à notre prochaine facture ?\n\n{first}",
      "un avoir contractuel",
    ),
    T(
      "technical",
      3,
      false,
      "Des expéditions ont disparu",
      "Bonjour,\n\nToutes les expéditions créées entre mardi et jeudi ont disparu du tableau de bord et de l'API, soit {loads} chargements. Pouvez-vous nous dire si elles sont récupérables ?\n\n{first}",
      "une perte de données",
    ),
    T(
      "account_access",
      1,
      false,
      "Ajouter deux licences",
      "Bonjour, deux coordinateurs arrivent lundi. Pourriez-vous ajouter deux licences et leur envoyer les invitations ?\n\n{first}",
      "un ajout de licences",
    ),
    T(
      "sales",
      0,
      false,
      "Démonstration du portail transporteurs",
      "Bonjour, nous aimerions une démonstration du portail transporteurs pour notre équipe d'exploitation le mois prochain.\n\n{first}",
      "une demande de démonstration",
    ),
    T(
      "privacy_security",
      1,
      false,
      "Questionnaire de sécurité fournisseur",
      "Notre équipe sécurité mène la revue annuelle des fournisseurs. Pouvez-vous nous envoyer votre rapport SOC 2 et remplir le questionnaire sous trois semaines ?\n\n{first}",
      "une revue de sécurité de routine",
    ),
  ],
  pt: [
    T(
      "billing",
      2,
      true,
      "Vou contestar esta cobrança",
      "Cancelámos as licenças adicionais em agosto e mesmo assim fomos cobrados {amount} na fatura {invoice}. Se não for reembolsado até segunda, vou contestar junto do banco.\n\n{first}",
      "um pedido de reembolso com ameaça de contestação",
    ),
    T(
      "technical",
      0,
      false,
      "Erro de ortografia na página de rastreio",
      'A vossa página de rastreio diz "Entrega estimda". Os nossos clientes veem isto em todas as encomendas. Corrijam, por favor.\n\n{first}',
      "um erro cosmético",
    ),
    T(
      "account_access",
      0,
      false,
      "Como mudo o e-mail das notificações?",
      "Pergunta rápida: onde altero o endereço para onde vão as notificações? Não encontro nas definições.\n\n{first}",
      "uma dúvida de configuração",
    ),
    T(
      "sales",
      1,
      false,
      "Orçamento para o módulo de pátio",
      "Gostaríamos de preços para o módulo de gestão de pátio em três armazéns, antes da reunião de orçamento da próxima semana.\n\n{first}",
      "um pedido de orçamento",
    ),
    T(
      "privacy_security",
      2,
      false,
      "Pedido de eliminação de dados (RGPD)",
      "Um ex-colaborador pediu-nos que apagássemos os seus dados pessoais. Eliminem a conta de j.moreau@{domain} e todos os dados associados e confirmem por escrito.\n\n{first}",
      "um pedido de eliminação de dados pessoais",
    ),
  ],
};
